#!/usr/bin/env bash

#cwd=$(pwd)
#cd $(dirname $0)

EXIT_SUCCESS=0
EXIT_FAILURE=1

function check() {

  if [ -n "$1" ]; then

    if [ -z "$(which $1 | grep -iv 'not found')" ]; then

      echo -en "\x1b[1;31;40m$1 not found\x21\x1b[0m\n" && exit $EXIT_FAILURE      
    fi
  else

    echo -en "\x1b[1;31;40mundefined\x21\x1b[0m\n" && exit $EXIT_FAILURE
  fi
}

check env
check dbus-launch
check python3

env LD_LIBRARY_PATH=`pwd`/lib:$LD_LIBRARY_PATH PYTHONPATH=`pwd`/lib/python3:`pwd`/lib/python3/lib-dynload:`pwd`/lib/python3/site-packages dbus-launch python3 $@

#cd $cwd
